// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuvmdwndgnjmpejzkfjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1dm1kd25kZ25qbXBlanprZmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjI2MzEsImV4cCI6MjA1OTc5ODYzMX0.hpMS3R-tEz6iqa7vT5MopuCJpThBQYx-m8cefxtKgu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);